### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ML-RogueAvenger** [Xruptor/xanBuffTimers#1]
Would it be possible to add the ability to ingore timers with long durtations (things more than 15-20 mins) or if possible ignore things longer than X duration that the user can specify

**Comment by Xruptor** [comment]
I'd have to check the code and see some sort of slider or what not can be added to ignore durations.  Currently the only option is to ignore infinite ones I think.  I had been work on a rework of this code but never got around to finishing it.  It's worth looking into though.  I'll take a look.
